# Inheritance

In [ ]:
# Inheritance
class parent:
    def __init__(self):
        self.name = 'Ammu'
class child(parent):
#    def __init__(self):
#        self.name = 'Natasha'
    def display(self):
        print(self.name)
obj_child = child()
obj_child.display()

In [ ]:
# Inheritance
class parent:
    def __init__(self):
        self.name = 'Ammu'
class child(parent):
    def __init__(self):
        self.name = 'Natasha'
    def display(self):
        print(self.name)
obj_child = child()
obj_child.display()

Natasha


# Lambda

In [ ]:
# Uses of lambda__1
def square(n):
    return n**2
print("Function: ",square(5))

square1 = lambda n:n**2
print("Lambda: ",square1(5))

Function:  25
Lambda:  25


In [ ]:
# Uses of lambda__2
def sum1(a,b):
    return a+b
print("Function: ",sum1(5,4))
sum2 = lambda a,b:a+b
print("Lambda: ",sum2(5,4))

Function:  9
Lambda:  9


# User Inputs

In [ ]:
# User input
n = int(input("give an integer number: "))
type(n)

give an integer number: 2


int

In [ ]:
# Multiple inputs
l = eval(input("Give many numbers using ,:"))
l

Give many numbers:1,2,3


(1, 2, 3)

In [ ]:
# Want to see the inputs in list
l2 = list(map(int,input().split()))
l2

1  3 5 6


[1, 3, 5, 6]

# Python Libraries

-----****-----
Numpy - Data Procesing
Pandas - Data manipulation, data cleaning
Seaborn,Matplotlib - Data visualization
-----****-----

# 1-D array

In [ ]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


# 2-D array

In [ ]:
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(b)
# size = 2*3  (row*column)

[[1 2 3]
 [4 5 6]]


# Initialize all elements as 0/1 on x X y array

In [ ]:
import numpy as np
print(np.zeros((3,5)))
print(np.ones((2,3)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


# Arrange the numbers between x & y

In [ ]:
import numpy as np
np.arange(1,11,3)

array([ 1,  4,  7, 10])

# Get n numbers between x & y

In [ ]:
import numpy as np
np.linspace(5,15,5)

array([ 5. ,  7.5, 10. , 12.5, 15. ])

# Fill xXy matrix/array with same number

In [ ]:
np.full((3,4),2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

# Fill matrix with random numbers

In [ ]:
np.random.random((2,3))

array([[0.59518119, 0.38206606, 0.73190421],
       [0.28617133, 0.90006516, 0.13161938]])

# Inserting the array:

# Check the shape of matrix

In [ ]:
d = np.array([[1,2],[3,4],[5,6],[7,8]])
print(d)
print(d.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


# Resize the array

In [ ]:
import numpy as np
s = np.random.random((2,3))
print("First matrix:")
print(s)
print("shape",s.shape)
s.shape = (6,1)
print("New:",s)
print("Shape:",s.shape)

First matrix:
[[0.48176843 0.22420293 0.55793242]
 [0.07944319 0.39981899 0.66301215]]
shape (2, 3)
New: [[0.48176843]
 [0.22420293]
 [0.55793242]
 [0.07944319]
 [0.39981899]
 [0.66301215]]
Shape: (6, 1)


# Find number of elements in array

In [ ]:
print(s.size)

6


In [ ]:
f = np.random.random((2,3))
f.size

6

# Find the datatype

In [ ]:
g = np.arange(1,10,3)
print(g," ",g.dtype)
h = np.arange(24,dtype=float)
print(h," ",h.dtype)

[1 4 7]   int32
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]   float64


In [ ]:
# Randint
i = np.random.randint(1,10)
i

2

In [ ]:
np.random.randint(1,5, size=(2,3), dtype='l')

array([[2, 4, 2],
       [1, 1, 1]])

# Numpy Array Mathematics:

# Addition

In [ ]:
# using numbers
import numpy as np
np.sum([20,30])

50

In [ ]:
# using variables
import numpy as np
a,b = 10,15
np.sum([a,b])

25

In [ ]:
# using axis
import numpy as np
print("Normal: ",np.sum([[1,2],[3,4]]))
print("Using Column: ",np.sum([[1,2],[3,4]],axis=0))  #column
print("Using Row: ",np.sum([[1,2],[3,4]],axis=1))  #row

Normal:  10
Using Column:  [4 6]
Using Row:  [3 7]


# Subtraction

In [ ]:
import numpy as np
np.subtract(15,8)

7

# Multiply, Divide & others

In [ ]:
import numpy as np
# 2 numbers
print("2 numbers: ",np.multiply(2,3))
# 2 array
a = np.array([2,3,4])
b = np.array([4,5,6])
print("2 array",np.multiply(a,b))

2 numbers:  6
2 array [ 8 15 24]


In [ ]:
np.divide(10,5)

2.0

In [ ]:
# exp,sqrt,sin,cos,log
h = np.array([2,3,4])
print("Exponent: ",np.exp(h))
print("Sqaure root: ",np.sqrt(h))
print("Sin: ",np.sin(h))
print("Cos: ",np.cos(h))
print("Log: ",np.log(h))

Exponent:  [ 7.3890561  20.08553692 54.59815003]
Sqaure root:  [1.41421356 1.73205081 2.        ]
Sin:  [ 0.90929743  0.14112001 -0.7568025 ]
Cos:  [-0.41614684 -0.9899925  -0.65364362]
Log:  [0.69314718 1.09861229 1.38629436]


# Array Comparison

In [ ]:
a = np.array([1,2,3])
b = np.array([5,2,6])
# check every element individually
print("Individual check: ",np.equal(a,b))
# check whole array
print("whole array check: ",np.array_equal(a,b))


Individual check:  [False  True False]
whole array check:  False


# Aggregate Function

In [ ]:
a = [1,2,4]
print("Sum: ",np.sum(a))
print("Minimum: ",np.min(a))
print("Mean: ",np.mean(a))
print("Median: ",np.median(a))
print("Coorelaton Coefficient: ",np.corrcoef(a))
print("Standard Deviation: ",np.std(a))

Sum:  7
Minimum:  1
Mean:  2.3333333333333335
Median:  2.0
Coorelaton Coefficient:  1.0
Standard Deviation:  1.247219128924647


# Broadcasting

In [ ]:
import numpy as np
a = np.array([[0,0,0],[1,2,3],[4,5,6],[5,6,7]])
b = np.array([0,1,2])
print("First Array + Second Array: \n",a+b )

First Array + Second Array: 
 [[0 1 2]
 [1 3 5]
 [4 6 8]
 [5 7 9]]


# Indexing & slicing

In [ ]:
c = np.array(['a','b','c','d','e','f','g','h'])
print(c[4:])

['e' 'f' 'g' 'h']


In [ ]:
# multiple dimension
d = np.array([[1,2,3],[4,5,6],[7,8,9],[0,1,2]])
print(d[0][0])
print(d[1:3,1:])
print(d[:,0])

1
[[5 6]
 [8 9]]
[1 4 7 0]


# Array manipulation

In [ ]:
import numpy as np
e = np.array([1,2,3])
f = np.array([4,5,6])
print("Normal concatenate: ",np.concatenate((e,f)))
print("Horizontally: ",np.hstack((e,f)))       # --->
print("Vertically: ",np.vstack((e,f)))         # !!
print("Column wise: ",np.column_stack((e,f)))  # !!

Normal concatenate:  [1 2 3 4 5 6]
Horizontally:  [1 2 3 4 5 6]
Vertically:  [[1 2 3]
 [4 5 6]]
Column wise:  [[1 4]
 [2 5]
 [3 6]]


# Splitting array

In [ ]:
x = np.arange(16).reshape(4,4)
print(x,"\n")
print(np.hsplit(x,2))
print(np.vsplit(x,2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]
